#!/bin/dash

#______________________________________________________________________________

# This package includes:
# A compiler for C code `clang`
# A compiler for C++ code `clang++`
# A language server for C and C++ `clangd`
# A code formatter for C and C++ `clang-format`
# sudo pacman -S --needed clang

# Traditional build automation tool.
# Executes instructions defined in a Makefile.
# Common for small projects or legacy codebases.
sudo pacman -S --needed make

# Fast build tool (executor).
# Runs build instructions generated by tools like CMake.
# Generally faster and more efficient than make.
sudo pacman -S --needed ninja

# Cross-platform build system generator.
# Reads CMakeLists.txt and generates build files
# for a real build tool (e.g., Ninja or Make).
# By default, it prefers Ninja if installed.
# Otherwise, it generates Makefiles for use with make.
sudo pacman -S --needed cmake

# bear is a rust-powered command that you add to the Makefile of your
# C++ project. It will create a `compile_commands.json` file that will allow
# clangd provide path completion when refering to header file.

# E.g. Example of usage in the Makefile of your project
# run:
# 	mkdir -p bin/
# 	bear -- clang++ -std=c++23 -Iinclude -Wconversion src/*.cpp -o bin/main
# 	./bin/main

# Without bear, if you had a header file in `include/Car.h` of your project,
# and then you have the file `src/Car.cpp` and you tried to reference the
# header file like this:
# `#include "Car.h"`,
# you would get an error message like this:
# 'Car.h' file not found clang (pp_file_not_found) [1, 10]

sudo pacman -S --needed bear

#______________________________________________________________________________
