#!/bin/dash

#______________________________________________________________________________

# This package includes:
# A compiler for C code `clang`
# A compiler for C++ code `clang++`
# A language server for C and C++ `clangd`
# A code formatter for C and C++ `clang-format`
# sudo pacman -S --needed clang

# Traditional build automation tool.
# Executes instructions defined in a Makefile.
# Common for small projects or legacy codebases.
sudo pacman -S --needed make

# Fast build tool (executor).
# Runs build instructions generated by tools like CMake.
# Generally faster and more efficient than make.
sudo pacman -S --needed ninja

# Cross-platform build system generator.
# Reads CMakeLists.txt and generates build files
# for a real build tool (e.g., Ninja or Make).
# By default, it prefers Ninja if installed.
# Otherwise, it generates Makefiles for use with make.
sudo pacman -S --needed cmake

#______________________________________________________________________________
