# Preload the wallpaper for monitor one: eDP-1 (ID 0)
# preload = $HOME/.config/hypr/images/mech_purple.jpg

# Preload the wallpaper for monitor two: HDMI-A-2 (ID 1) 
# preload = $HOME/.config/hypr/images/blue_eyed_blonde.jpg

#______________________________________________________________________________

# To figure out the name of your monitor, run this command
# hyprctl monitors

# E.g. If you see something like this:
# Monitor eDP-1 (ID 0):
# Then that means your monitor name is eDP-1
# wallpaper = eDP-1,$HOME/.config/hypr/images/mech_purple.jpg

wallpaper {
    monitor = eDP-1
    path = $HOME/.config/hypr/hyprpaper-images/edp_1_wallpaper.png
    fit_mode = fill
}

# E.g. If you see something like this:
# Monitor HDMI-A-2 (ID 1):
# Then that means your monitor name is HDMI-A-2
# wallpaper = HDMI-A-2,$HOME/.config/hypr/images/mech_purple.jpg

# wallpaper {
#     monitor = HDMI-A-2
#     path = $HOME/.config/hypr/images/mech_purple.jpg
#     fit_mode = fill
# }

#______________________________________________________________________________

# Gets rid of the random text at the bottom of the wallpaper
splash = false 

# Disable IPC to save battery life
ipc = false

#______________________________________________________________________________
